.TH "src/AP_Destiler.cpp" 3 "IntelligentDestiller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/AP_Destiler.cpp \- Application file for the MD project\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'AP\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdestiler\fP ()"
.br
.RI "Destiler function\&. "
.in -1c
.SH "Detailed Description"
.PP 
Application file for the MD project\&. 


.PP
\fBAuthor\fP
.RS 4
Sérgio Carmo
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void destiler ()"

.PP
Destiler function\&. APP Header\&.

.PP
This function is responsible for managing the operation of the machine\&. BMB_FLAG, RAQ_FLAG BMB_FLAG and RAQ_FLAG are flags that are used to control the operation of the machine\&. BMB_FLAG is used to control the operation of the water pump\&. RAQ_FLAG is used to control the operation of the water heater resistor\&. 
.PP
\fBNote\fP
.RS 4
BMB_FLAG and RAQ_FLAG are used to control the operation of the machine\&. 

.PP
BMB_FLAG is used to control the operation of the water pump\&. 

.PP
RAQ_FLAG is used to control the operation of the water heater resistor\&.
.RE
.PP
< Debug information logging

.PP
Call the indicatorsManagement function to manage the indicators of the machine

.PP
Call the modeManagement function to manage the different modes of the machine (Auto and Manual)

.PP
WORKING BLOCK

.PP
Flag to control the operation of the water pump

.PP
If the water level is at the maximum, the water pump is turned off\&. If the water level is at the minimum or there is an alarm, the water pump is turned on\&. 
.PP
\fBNote\fP
.RS 4
If the water level is at the maximum, the water pump is turned off\&. 

.PP
If the water level is at the minimum or there is an alarm, the water pump is turned on\&.
.RE
.PP
If the water level is at the maximum turn off the water pump

.PP
Turn off the water pump

.PP
Set the water pump to OFF in the web interface

.PP
If the water level is at the minimum or at the alarm level, turn on the water pump

.PP
Turn on the water pump

.PP
Control of the operation of the water heater resistor

.PP
If the water level is at the maximum, the water heater resistor is turned off\&. If the water level is at the minimum or there is an alarm, the water heater resistor is turned on\&. 
.PP
\fBNote\fP
.RS 4
If the water level is at the maximum, the water heater resistor is turned off\&. 

.PP
If the water level is at the minimum or there is an alarm, the water heater resistor is turned on\&. *
.RE
.PP
If the water level is at the maximum or min or is not at alarm lvl, turn ON the water heater resistor

.PP
If the water level is at the alarmlvl, turn OFF the water heater resistor

.PP
BMB, RAQ, V_IN, V_OUT BMB, RAQ, V_IN, V_OUT are variables that are used to control the operation of the machine\&. BMB is used to control the operation of the water pump\&. RAQ is used to control the operation of the water heater resistor\&. V_IN is used to control the operation of the water inlet valve\&. V_OUT is used to control the operation of the water outlet valve\&. 
.PP
\fBNote\fP
.RS 4
BMB is used to control the operation of the water pump\&. 

.PP
RAQ is used to control the operation of the water heater resistor\&. 

.PP
V_IN is used to control the operation of the water inlet valve\&. 

.PP
V_OUT is used to control the operation of the water outlet valve\&.
.RE
.PP
If the water pump is on and the machine is in auto mode or the water pump is on in manual mode and the water level is not at the maximum, turn on the water pump

.PP
If the water heater resistor is on and the machine is in auto mode or the water heater resistor is on in manual mode and the alarm is not on, turn on the water heater resistor

.PP
If the water inlet valve is on and the machine is in auto mode or the water inlet valve is on in manual mode and the alarm is not on, turn on the water inlet valve

.PP
If the water outlet valve is on and the machine is in auto mode or the water outlet valve is on in manual mode and the alarm is not on, turn on the water outlet valve

.PP
Set the Pump object to the BMB variable value Set the Pump object to the BMB variable value\&. 
.PP
\fBNote\fP
.RS 4
Set the Pump object to the BMB variable value\&.
.RE
.PP
Set the Resistor object to the RAQ variable value Set the Resistor object to the RAQ variable value\&. 
.PP
\fBNote\fP
.RS 4
Set the Resistor object to the RAQ variable value\&.
.RE
.PP
Set the Valve Water In object Set the Valve Water In object to the V_IN variable value\&. 
.PP
\fBNote\fP
.RS 4
Set the Valve Water In object to the V_IN variable value\&.
.RE
.PP
Set the Valve Water Out object Set the Valve Water Out object to the V_OUT variable value\&. 
.PP
\fBNote\fP
.RS 4
Set the Valve Water Out object to the V_OUT variable value\&.
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IntelligentDestiller from the source code\&.
