.TH "C:/workspace/Projeto/InteligentDestiller/src/AP_main.cpp" 3 "IntelligentDestiller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/workspace/Projeto/InteligentDestiller/src/AP_main.cpp \- Main file for the MD project\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'AP\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "AsyncWebSocket \fBws\fP ('/ws')"
.br
.RI "Debug mode\&. "
.ti -1c
.RI "AsyncWebServer \fBserver\fP (80)"
.br
.RI "AsyncWebSocket object to handle websocket connections\&. "
.ti -1c
.RI "void \fBsetup\fP ()"
.br
.RI "Create a webserver object that listens for HTTP request on port 80\&. "
.ti -1c
.RI "void \fBloop\fP (void)"
.br
.RI "Loop function to run the machine operation\&. "
.ti -1c
.RI "void \fBloop2\fP (void *pvParameters)"
.br
.RI "Main function to run the second core operation\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBDEBUG\fP = 1"
.br
.RI "WebServer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Main file for the MD project\&. 


.PP
\fBAuthor\fP
.RS 4
Sérgio Carmo
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void loop (void )"

.PP
Loop function to run the machine operation\&. This function is responsible for running the machine operation\&.

.PP
\fBNote\fP
.RS 4
Read inputs 

.PP
Destiler function to operate the machine 

.PP
Update outputs
.RE
.PP
\fBSee also\fP
.RS 4
\fBreadInputs()\fP 

.PP
\fBdestiler()\fP 

.PP
\fBupdateOutputsWeb()\fP 
.RE
.PP
Destiler function to operate the machine

.PP
Update outputs
.SS "void loop2 (void * pvParameters)"

.PP
Main function to run the second core operation\&. MAIN\&.

.PP
This function is responsible for running the second core operation\&.

.PP
\fBNote\fP
.RS 4
Initiate WIFI 

.PP
Cleanup clients 

.PP
WebTimer function
.RE
.PP
\fBSee also\fP
.RS 4
\fBinitWIFI()\fP 

.PP
ws\&.cleanupClients() 

.PP
\fBwebTimer()\fP
.RE
.PP
\fBParameters\fP
.RS 4
\fIpvParameters\fP 
.RE
.PP
Main loop

.PP
Cleanup clients

.PP
WebTimer function
.SS "AsyncWebServer server (80 )"

.PP
AsyncWebSocket object to handle websocket connections\&. 
.SS "void setup ()"

.PP
Create a webserver object that listens for HTTP request on port 80\&. Setup function to initiate all the necessary functions to run the machine

.PP
This function is responsible for initiating all the necessary functions to run the machine\&.

.PP
\fBNote\fP
.RS 4
Initiate all pins as inputs 

.PP
Initiate all pins as outputs 

.PP
Initiate Serial communication 

.PP
Initiate MultiCore 

.PP
Initiate SPIFFS 

.PP
Read inputs 

.PP
Update outputs 

.PP
Setup Routes 

.PP
Add handler to the server 
.RE
.PP
Initiate all pins as inputs

.PP
Initiate all pins as outputs

.PP
Initiate Serial communication (9600 bps)

.PP
Test IO

.PP
Initiate MultiCore (Second Core)

.PP
Initiate SPIFFS (SPI Flash File System)

.PP
Read inputs for the first time

.PP
Update outputs for the web interface

.PP
Initiate WIFI

.PP
Setup Routes

.PP
Add handler to the server (Websocket)
.SS "AsyncWebSocket ws ('/ws' )"

.PP
Debug mode\&. AsyncWebSocket object to handle websocket connections 
.SH "Variable Documentation"
.PP 
.SS "bool DEBUG = 1"

.PP
WebServer\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IntelligentDestiller from the source code\&.
