.TH "src Directory Reference" 3 "IntelligentDestiller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAP_Destiler\&.cpp\fP"
.br
.RI "Application file for the MD project\&. "
.ti -1c
.RI "file \fBAP_main\&.cpp\fP"
.br
.RI "Main file for the MD project\&. "
.ti -1c
.RI "file \fBAP_Web\&.cpp\fP"
.br
.RI "Web Server functions\&. "
.ti -1c
.RI "file \fBMD_IO\&.cpp\fP"
.br
.RI "IO functions for the MD project <This file contains the IO functions for the MD project that are used to control the Machine and its peripherals using the ESP32 GPIOs and the Web Interface of the project\&.> "
.ti -1c
.RI "file \fBMD_Serial\&.cpp\fP"
.br
.RI "Serial functions for the MD project\&. "
.ti -1c
.RI "file \fBMD_Test_IOs\&.cpp\fP"
.br
.RI "Test I/Os for the MD project\&. "
.ti -1c
.RI "file \fBMD_Timer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMD_Web_Handlers\&.cpp\fP"
.br
.RI "Web Handlers for the MD project\&. "
.ti -1c
.RI "file \fBMD_Web_IO_Mngmnt\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMD_wifi\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOS_FS\&.cpp\fP"
.br
.RI "File System functions\&. "
.ti -1c
.RI "file \fBOS_GPIO\&.cpp\fP"
.br
.RI "GPIO functions\&. "
.ti -1c
.RI "file \fBOS_multi_core\&.cpp\fP"
.br
.RI "Operating System MultiCore functions\&. "
.in -1c
