.TH "src/MD_IO.cpp" 3 "IntelligentDestiller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/MD_IO.cpp \- IO functions for the MD project <This file contains the IO functions for the MD project that are used to control the Machine and its peripherals using the ESP32 GPIOs and the Web Interface of the project\&.>  

.SH SYNOPSIS
.br
.PP
\fR#include 'MD\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtoggleIndAuto\fP ()"
.br
.RI "Toggle the Auto Mode of the Machine\&. "
.ti -1c
.RI "void \fBtoggleAutoMode\fP ()"
.br
.RI "Toggle the Auto Mode of the Machine using a switch connected to the ESP32 GPIO 4 (D4) "
.ti -1c
.RI "void \fBindicatorsManagement\fP ()"
.br
.ti -1c
.RI "void \fBmodeManagement\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
IO functions for the MD project <This file contains the IO functions for the MD project that are used to control the Machine and its peripherals using the ESP32 GPIOs and the Web Interface of the project\&.> 


.PP
\fBAuthor\fP
.RS 4
Sérgio Carmo
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void indicatorsManagement ()"
INDICATORS BLOCK

.PP
Set the maximum water level indicator

.PP
Set the minimum water level indicator

.PP
Set the alarm indicator

.PP
Set the manual mode indicator
.SS "void modeManagement ()"
MACHINE MODE MANAGEMENT BLOCK ///////////////////////////////////////////////////////////////////////////////////// If the machine is in manual mode, turn off the auto mode indicator

.PP
Toggle the auto mode

.PP
Set the auto mode indicator to the web value of the auto mode

.PP
Set the auto mode indicator to OFF

.PP
Set the auto mode to OFF in the web interface

.PP
If the machine is in manual mode, turn off the timer

.PP
Turn off the timer
.SS "void toggleAutoMode ()"

.PP
Toggle the Auto Mode of the Machine using a switch connected to the ESP32 GPIO 4 (D4) 
.PP
\fBNote\fP
.RS 4
This function is used to toggle the Auto Mode of the Machine using a switch connected to the ESP32 GPIO 4 (D4) 
.RE
.PP
current state of the button

.PP
previous state of the button

.PP
current state of the button

.PP
the last time the output pin was toggled

.PP
the debounce time; increase if the output flickers

.PP
read the state of the switch into a local variable

.PP
If the switch changed, due to noise or pressing

.PP
reset the debouncing timer

.PP
if the switch value has been stable for a while

.PP
if the button state has changed

.PP
save the new state

.PP
if the button state is HIGH

.PP
Toggle Auto Mode

.PP
save the current state as the last state, for next time through the loop
.SS "void toggleIndAuto ()"

.PP
Toggle the Auto Mode of the Machine\&. 
.PP
\fBNote\fP
.RS 4
This function is used to toggle the Auto Mode of the Machine 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IntelligentDestiller from the source code\&.
