.TH "src/MD_Serial.cpp" 3 "IntelligentDestiller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/MD_Serial.cpp \- Serial functions for the MD project\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'MD\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitSerial\fP ()"
.br
.RI "Initialize Serial Terminal\&. "
.ti -1c
.RI "void \fBsPrint\fP (char *abc)"
.br
.RI "Serial Print Functions\&. "
.ti -1c
.RI "void \fBsPrintLn\fP (char *abc)"
.br
.RI "Print a string to the Serial Terminal with a line break\&. "
.ti -1c
.RI "void \fBsPrintStr\fP (String abc)"
.br
.RI "Print a string to the Serial Terminal\&. "
.ti -1c
.RI "void \fBsPrintLnStr\fP (String abc)"
.br
.RI "Print a string to the Serial Terminal with a line break\&. "
.ti -1c
.RI "void \fBsPrintNbr\fP (int nbr)"
.br
.RI "Print a number to the Serial Terminal\&. "
.ti -1c
.RI "void \fBsPrintLnNbr\fP (int nbr)"
.br
.RI "Print a number to the Serial Terminal with a line break\&. "
.in -1c
.SH "Detailed Description"
.PP 
Serial functions for the MD project\&. 


.PP
\fBAuthor\fP
.RS 4
Sérgio Carmo
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void initSerial ()"

.PP
Initialize Serial Terminal\&. Set timer status\&.

.PP
Initialize Serial Communications with the default baud rate of 9600 bps

.PP
\fBNote\fP
.RS 4
This function is used to initialize the Serial Communications with the default baud rate of 9600 bps 

.PP
This function is called in the \fBsetup()\fP function of the main program 

.PP
This function is used to print the initial message to the Serial Terminal 
.RE
.PP
Initialize Serial Communications with the default baud rate of 9600 bps
.SS "void sPrint (char * abc)"

.PP
Serial Print Functions\&. Inicia a serial\&.

.PP
Print a string to the Serial Terminal 
.PP
\fBParameters\fP
.RS 4
\fIabc\fP 
.RE
.PP
\fBNote\fP
.RS 4
This function is used to print a string to the Serial Terminal with no line break 
.RE
.PP

.SS "void sPrintLn (char * abc)"

.PP
Print a string to the Serial Terminal with a line break\&. Print string\&.

.PP
\fBParameters\fP
.RS 4
\fIabc\fP 
.RE
.PP
\fBNote\fP
.RS 4
This function is used to print a string to the Serial Terminal with a line break 
.RE
.PP

.SS "void sPrintLnNbr (int nbr)"

.PP
Print a number to the Serial Terminal with a line break\&. Print string with new line\&.

.PP
\fBParameters\fP
.RS 4
\fInbr\fP 
.RE
.PP
\fBNote\fP
.RS 4
This function is used to print a number to the Serial Terminal with a line break 
.RE
.PP

.SS "void sPrintLnStr (String abc)"

.PP
Print a string to the Serial Terminal with a line break\&. Print number\&.

.PP
\fBParameters\fP
.RS 4
\fIabc\fP 
.RE
.PP
\fBNote\fP
.RS 4
This function is used to print a string to the Serial Terminal with a line break 
.RE
.PP

.SS "void sPrintNbr (int nbr)"

.PP
Print a number to the Serial Terminal\&. Print string\&.

.PP
\fBParameters\fP
.RS 4
\fInbr\fP 
.RE
.PP
\fBNote\fP
.RS 4
This function is used to print a number to the Serial Terminal with no line break 
.RE
.PP

.SS "void sPrintStr (String abc)"

.PP
Print a string to the Serial Terminal\&. Print string with new line\&.

.PP
\fBParameters\fP
.RS 4
\fIabc\fP 
.RE
.PP
\fBNote\fP
.RS 4
This function is used to print a string to the Serial Terminal with no line break 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IntelligentDestiller from the source code\&.
