.TH "src/MD_Test_IOs.cpp" 3 "IntelligentDestiller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/MD_Test_IOs.cpp \- Test I/Os for the MD project\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'MD\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBdelayT\fP   500"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_IO\fP ()"
.br
.RI "Test I/Os\&. "
.in -1c
.SH "Detailed Description"
.PP 
Test I/Os for the MD project\&. 


.PP
\fBAuthor\fP
.RS 4
Sérgio Carmo
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define delayT   500"

.SH "Function Documentation"
.PP 
.SS "void test_IO ()"

.PP
Test I/Os\&. Print number with new line\&.

.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP
Test I/O Indicador Maximo

.PP
Test I/O Indicador Minimo

.PP
Test I/O Indicador Alarme

.PP
Test I/O Indicador Manual

.PP
Test I/O Indicador Auto

.PP
Test I/O Indicador Valvula Entrada

.PP
Test I/O Indicador Valvula Saida

.PP
Test I/O Indicador Resistor
.SH "Author"
.PP 
Generated automatically by Doxygen for IntelligentDestiller from the source code\&.
