.TH "C:/workspace/Projeto/InteligentDestiller/src/MD_Timer.cpp" 3 "IntelligentDestiller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/workspace/Projeto/InteligentDestiller/src/MD_Timer.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'MD\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsendTimer\fP ()"
.br
.RI "Send timer to web\&. "
.ti -1c
.RI "long \fBwebTimer\fP (String op, int16_t amount)"
.br
.RI "Web timer function to manage the timer operations in the web interface\&. "
.ti -1c
.RI "bool \fBgetTimerStatus\fP ()"
.br
.RI "Get the Timer Status object to get the timer status (ON/OFF) "
.ti -1c
.RI "int \fBgetTimerSecound\fP ()"
.br
.RI "Get the Timer Secound object to get the timer secound\&. "
.ti -1c
.RI "int \fBgetTimerMinute\fP ()"
.br
.RI "Get the Timer Minute object to get the timer minute\&. "
.ti -1c
.RI "int \fBgetTimerHour\fP ()"
.br
.RI "Get the Timer Hour object to get the timer hour\&. "
.ti -1c
.RI "void \fBsetTimer\fP (bool stat)"
.br
.RI "Set the Timer object to set the timer status (ON/OFF) "
.ti -1c
.RI "void \fBadd1s\fP ()"
.br
.RI "Add 1 secound to timer\&. "
.ti -1c
.RI "void \fBadd5s\fP ()"
.br
.RI "Add 5 secounds to timer\&. "
.ti -1c
.RI "void \fBadd10s\fP ()"
.br
.RI "Add 10 secounds to timer\&. "
.ti -1c
.RI "void \fBadd1m\fP ()"
.br
.RI "Add 1 minute to timer\&. "
.ti -1c
.RI "void \fBadd5m\fP ()"
.br
.RI "Add 5 minutes to timer\&. "
.ti -1c
.RI "void \fBadd10m\fP ()"
.br
.RI "Add 10 minutes to timer\&. "
.ti -1c
.RI "void \fBrem1s\fP ()"
.br
.RI "Remove 1 secound from timer\&. "
.ti -1c
.RI "void \fBrem5s\fP ()"
.br
.RI "Remove 5 secounds from timer\&. "
.ti -1c
.RI "void \fBrem10s\fP ()"
.br
.RI "Remove 10 secounds from timer\&. "
.ti -1c
.RI "void \fBrem1m\fP ()"
.br
.RI "Remove 1 minute from timer\&. "
.ti -1c
.RI "void \fBrem5m\fP ()"
.br
.RI "Remove 5 minutes from timer\&. "
.ti -1c
.RI "void \fBrem10m\fP ()"
.br
.RI "Remove 10 minutes from timer\&. "
.ti -1c
.RI "void \fBresetTimer\fP ()"
.br
.RI "Reset timer\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBflagTimerStatus\fP = \fBOFF\fP"
.br
.RI "Timer Functions\&. "
.ti -1c
.RI "const unsigned long \fBupdateInterval\fP = 1000"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void add10m ()"

.PP
Add 10 minutes to timer\&. Add 5 minutes to timer\&. 
.SS "void add10s ()"

.PP
Add 10 secounds to timer\&. Add 5 secounds to timer\&. 
.SS "void add1m ()"

.PP
Add 1 minute to timer\&. Add 10 secounds to timer\&. 
.SS "void add1s ()"

.PP
Add 1 secound to timer\&. Get timer status\&. 
.SS "void add5m ()"

.PP
Add 5 minutes to timer\&. Add 1 minute to timer\&. 
.SS "void add5s ()"

.PP
Add 5 secounds to timer\&. Add 1 secound to timer\&. 
.SS "int getTimerHour ()"

.PP
Get the Timer Hour object to get the timer hour\&. Get timer minute\&.

.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
Return the timer hours left in the timer
.SS "int getTimerMinute ()"

.PP
Get the Timer Minute object to get the timer minute\&. Get timer secound\&.

.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
Return the timer minutes left in the timer
.SS "int getTimerSecound ()"

.PP
Get the Timer Secound object to get the timer secound\&. Timer for web operations\&.

.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
Return the timer seconds left in the timer 
.br

.SS "bool getTimerStatus ()"

.PP
Get the Timer Status object to get the timer status (ON/OFF) Get timer hour\&.

.PP
\fBNote\fP
.RS 4
This function is called by the processor function in AP_Destiller\&.cpp 
.RE
.PP
\fBReturns\fP
.RS 4
true 

.PP
false 
.RE
.PP
Return the timer status (ON/OFF)
.SS "void rem10m ()"

.PP
Remove 10 minutes from timer\&. Remove 5 minutes from timer\&. 
.SS "void rem10s ()"

.PP
Remove 10 secounds from timer\&. Remove 5 secounds from timer\&. 
.SS "void rem1m ()"

.PP
Remove 1 minute from timer\&. Remove 10 secounds from timer\&. 
.SS "void rem1s ()"

.PP
Remove 1 secound from timer\&. Add 10 minutes to timer\&. 
.SS "void rem5m ()"

.PP
Remove 5 minutes from timer\&. Remove 1 minute from timer\&. 
.SS "void rem5s ()"

.PP
Remove 5 secounds from timer\&. Remove 1 secound from timer\&. 
.SS "void resetTimer ()"

.PP
Reset timer\&. Remove 10 minutes from timer\&. 
.SS "void sendTimer ()"

.PP
Send timer to web\&. This function sends the timer to the web interface to update the timer display in the web interface\&.

.PP
\fBNote\fP
.RS 4
This function is called by the webTimer function in \fBMD_Timer\&.cpp\fP 
.RE
.PP
Old values to compare with the new values to send updates only when the timer changes

.PP
Only send updates if the timer has changed

.PP
Send the timer to the web interface

.PP
Create the message to send to the web interface as a JSON object

.PP
Send the message to the web interface

.PP
Update the old values
.SS "void setTimer (bool stat)"

.PP
Set the Timer object to set the timer status (ON/OFF) Reset timer\&.

.PP
\fBParameters\fP
.RS 4
\fIstat\fP 
.RE
.PP
Set the timer status (ON/OFF)
.SS "long webTimer (String op, int16_t amount)"

.PP
Web timer function to manage the timer operations in the web interface\&. Timer Functions calls\&.

.PP
This function is responsible for managing the timer operations\&.

.PP
\fBParameters\fP
.RS 4
\fIop\fP 
.br
\fIamount\fP 
.RE
.PP
\fBReturns\fP
.RS 4
unsigned long 
.RE
.PP
Timer operations to add, remove or reset the timer value in miliseconds

.PP
Add time to the timer

.PP
Add 1 second

.PP
Add 5 seconds

.PP
Add 10 seconds

.PP
Add 1 minute

.PP
Add 5 minutes

.PP
Add 10 minutes

.PP
Remove time from the timer

.PP
Remove 1 second

.PP
Remove 5 seconds

.PP
Remove 10 seconds

.PP
Remove 1 minute

.PP
Remove 5 minutes

.PP
Remove 10 minutes

.PP
Reset the timer to 0

.PP
Timer management to decrease the timer every second and turn it off when it reaches 0 seconds left

.PP
Decrease the timer every second if the timer is ON

.PP
Turn off the timer when it reaches 0 seconds left

.PP
Only send updates at the defined interval

.PP
Send the timer to the web interface
.SH "Variable Documentation"
.PP 
.SS "bool flagTimerStatus = \fBOFF\fP"

.PP
Timer Functions\&. 
.SS "const unsigned long updateInterval = 1000"

.SH "Author"
.PP 
Generated automatically by Doxygen for IntelligentDestiller from the source code\&.
