.TH "src/MD_Web_IO_Mngmnt.cpp" 3 "IntelligentDestiller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/MD_Web_IO_Mngmnt.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'MD\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBupdateOutputsWeb\fP ()"
.br
.RI "Output variables image\&. "
.ti -1c
.RI "bool \fBgetAutoModeWeb\fP ()"
.br
.RI "GETS BLOCK\&. "
.ti -1c
.RI "bool \fBgetResistorWeb\fP ()"
.br
.RI "Get the Ind Min object\&. "
.ti -1c
.RI "bool \fBgetValv_Water_InWeb\fP ()"
.br
.RI "Get the Ind Alarm object\&. "
.ti -1c
.RI "bool \fBgetValv_Water_OutWeb\fP ()"
.br
.RI "Get the Valv Water Out object\&. "
.ti -1c
.RI "bool \fBgetPumpWeb\fP ()"
.br
.RI "Get the Pump object\&. "
.ti -1c
.RI "void \fBsetAutoModeWeb\fP (bool state)"
.br
.RI "SETS BLOCK\&. "
.ti -1c
.RI "void \fBsetPumpWeb\fP (bool state)"
.br
.RI "Set the Pump object\&. "
.ti -1c
.RI "void \fBsetValveWaterInWeb\fP (bool state)"
.br
.RI "Set the Valve Water In object\&. "
.ti -1c
.RI "void \fBsetValveWaterOutWeb\fP (bool state)"
.br
.RI "Set the Valve Water Out object\&. "
.ti -1c
.RI "void \fBsetResistorWeb\fP (bool state)"
.br
.RI "Set the Resistor object\&. "
.ti -1c
.RI "void \fBtoggleAutoModeWeb\fP ()"
.br
.RI "TOGGLES BLOCK\&. "
.ti -1c
.RI "void \fBtogglePumpWeb\fP ()"
.br
.RI "Toggle Pump Web\&. "
.ti -1c
.RI "void \fBtoggleValveWaterInWeb\fP ()"
.br
.RI "Toggle Valve Water In Web\&. "
.ti -1c
.RI "void \fBtoggleValveWaterOutWeb\fP ()"
.br
.RI "Toggle Valve Water Out Web\&. "
.ti -1c
.RI "void \fBtoggleResistorWeb\fP ()"
.br
.RI "Toggle Resistor Web\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint8_t \fBoutputVarsImageWeb\fP [9]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Sérgio Carmo (19749@ipportalegre.pt) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "bool getAutoModeWeb ()"

.PP
GETS BLOCK\&. Get the Ind Max object

.PP
This function returns the state of the max indicator\&.

.PP
\fBReturns\fP
.RS 4
true 

.PP
false 
.RE
.PP

.SS "bool getPumpWeb ()"

.PP
Get the Pump object\&. This function returns the state of the water pump\&.

.PP
\fBReturns\fP
.RS 4
true 

.PP
false 
.RE
.PP

.SS "bool getResistorWeb ()"

.PP
Get the Ind Min object\&. This function returns the state of the min indicator\&.

.PP
\fBReturns\fP
.RS 4
true 

.PP
false 
.RE
.PP

.SS "bool getValv_Water_InWeb ()"

.PP
Get the Ind Alarm object\&. This function returns the state of the alarm indicator\&.

.PP
\fBReturns\fP
.RS 4
true 

.PP
false 
.RE
.PP

.SS "bool getValv_Water_OutWeb ()"

.PP
Get the Valv Water Out object\&. This function returns the state of the water out valve\&.

.PP
\fBReturns\fP
.RS 4
true 

.PP
false 
.RE
.PP

.SS "void setAutoModeWeb (bool state)"

.PP
SETS BLOCK\&. Set the Auto Mode object

.PP
This function sets the state of the auto mode\&.

.PP
\fBParameters\fP
.RS 4
\fIstate\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP
Static variable to store the old state

.PP
Set the auto indicator to ON

.PP
Set the old state to the current state

.PP
Set the auto indicator to OFF

.PP
Set the old state to the current state
.SS "void setPumpWeb (bool state)"

.PP
Set the Pump object\&. This function sets the state of the pump\&.

.PP
\fBParameters\fP
.RS 4
\fIstate\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP
Static variable to store the old state

.PP
Set the pump to ON

.PP
Set the old state to the current state

.PP
Set the pump to OFF

.PP
Set the old state to the current state
.SS "void setResistorWeb (bool state)"

.PP
Set the Resistor object\&. This function sets the state of the resistor\&.

.PP
\fBParameters\fP
.RS 4
\fIstate\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP
Static variable to store the old state

.PP
Set the resistor to ON

.PP
Set the old state to the current state

.PP
Set the resistor to OFF

.PP
Set the old state to the current state
.SS "void setValveWaterInWeb (bool state)"

.PP
Set the Valve Water In object\&. This function sets the state of the water in valve\&.

.PP
\fBParameters\fP
.RS 4
\fIstate\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP
Static variable to store the old state

.PP
Set the water in valve to ON

.PP
Set the old state to the current state

.PP
Set the water in valve to OFF

.PP
Set the old state to the current state
.SS "void setValveWaterOutWeb (bool state)"

.PP
Set the Valve Water Out object\&. This function sets the state of the water out valve\&.

.PP
\fBParameters\fP
.RS 4
\fIstate\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP
Static variable to store the old state

.PP
Set the water out valve to ON

.PP
Set the old state to the current state

.PP
Set the water out valve to OFF

.PP
Set the old state to the current state
.SS "void toggleAutoModeWeb ()"

.PP
TOGGLES BLOCK\&. Toggle Auto Mode Web

.PP
This function toggles the auto mode\&.

.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP
Get the auto indicator state

.PP
Toggle the auto indicator state

.PP
Set the auto indicator state

.PP
Toggle the auto indicator state

.PP
Set the auto indicator state
.SS "void togglePumpWeb ()"

.PP
Toggle Pump Web\&. This function toggles the pump\&.

.PP
\fBReturns\fP
.RS 4
void Toggle Pump 
.RE
.PP
Get the pump state

.PP
Toggle the pump state

.PP
Set the pump state

.PP
Print the pump state

.PP
Print the pump state

.PP
Toggle the pump state

.PP
Set the pump state

.PP
Print the pump state

.PP
Print the pump state
.SS "void toggleResistorWeb ()"

.PP
Toggle Resistor Web\&. This function toggles the resistor\&.

.PP
\fBReturns\fP
.RS 4
void Toggle Resistor 
.RE
.PP
Get the resistor state

.PP
Toggle the resistor state

.PP
Set the resistor state

.PP
Toggle the resistor state

.PP
Set the resistor state
.SS "void toggleValveWaterInWeb ()"

.PP
Toggle Valve Water In Web\&. This function toggles the water in valve\&.

.PP
\fBReturns\fP
.RS 4
void Toggle Valve Water In 
.RE
.PP
Get the water in valve state

.PP
Toggle the water in valve state

.PP
Set the water in valve state

.PP
Toggle the water in valve state

.PP
Set the water in valve state
.SS "void toggleValveWaterOutWeb ()"

.PP
Toggle Valve Water Out Web\&. This function toggles the water out valve\&.

.PP
\fBReturns\fP
.RS 4
void Toggle Valve Water Out 
.RE
.PP
Get the water out valve state

.PP
If the water out valve state is OFF and the manual mode is ON

.PP
Toggle the water out valve state

.PP
Set the water out valve state

.PP
Toggle the water out valve state

.PP
Set the water out valve state
.SS "void updateOutputsWeb ()"

.PP
Output variables image\&. FUNCTIONS BLOCK

.PP
Update Outputs Web

.PP
This function updates the outputs for the web interface\&.

.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP
Update the resistor state

.PP
Update the pump state

.PP
Update the water out valve state

.PP
Update the water in valve state

.PP
Update the alarm state

.PP
Update the water min state

.PP
Update the water max state

.PP
Update the manual mode state

.PP
outputVarsImageWeb[7] = \fBgetIndAuto()\fP; /// Update the auto indicator state
.SH "Variable Documentation"
.PP 
.SS "uint8_t outputVarsImageWeb[9]"

.SH "Author"
.PP 
Generated automatically by Doxygen for IntelligentDestiller from the source code\&.
