.TH "src/OS_FS.cpp" 3 "IntelligentDestiller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/OS_FS.cpp \- File System functions\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'OS\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitFS\fP ()"
.br
.RI "Initialize Serial Terminal\&. "
.in -1c
.SH "Detailed Description"
.PP 
File System functions\&. 


.PP
\fBAuthor\fP
.RS 4
Sérgio Carmo (19749@ipportalegre.pt) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void initFS ()"

.PP
Initialize Serial Terminal\&. LittleFS\&.

.PP
Initialize File System (SPIFFS)

.PP
This function is responsible for initializing the File System (SPIFFS)\&.

.PP
\fBNote\fP
.RS 4
Initialize SPIFFS
.RE
.PP
\fBReturns\fP
.RS 4
void
.RE
.PP
.PP
.nf
initFS();
.fi
.PP
 Initialize SPIFFS
.SH "Author"
.PP 
Generated automatically by Doxygen for IntelligentDestiller from the source code\&.
