.TH "C:/workspace/Projeto/InteligentDestiller/src/OS_multi_core.cpp" 3 "IntelligentDestiller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/workspace/Projeto/InteligentDestiller/src/OS_multi_core.cpp \- Operating System MultiCore functions\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'OS\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitMultiCore\fP ()"
.br
.RI "Function to initiate the 2nd core to run 'loop2' function\&. "
.in -1c
.SH "Detailed Description"
.PP 
Operating System MultiCore functions\&. 


.PP
\fBAuthor\fP
.RS 4
Sérgio Carmo
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void initMultiCore ()"

.PP
Function to initiate the 2nd core to run 'loop2' function\&. Main loop to run in core 1\&.

.PP
<Function to initiate the 2nd core> Implements the 2nd core option to run 'loop2' function

.PP
Function to implement the task

.PP
Name of the task

.PP
Stack size in words

.PP
Task input parameter

.PP
Priority of the task

.PP
Task handle\&.

.PP
Core where the task should run
.SH "Author"
.PP 
Generated automatically by Doxygen for IntelligentDestiller from the source code\&.
