AP_Web.cpp
void handleWebSocketMessage(void *arg, uint8_t *data, size_t len)
Definitions.
Variables and Constants for Web Server and WebSocket Server Web Server and WebSocket Server variables These variables are used to create the Web Server and WebSocket Server. These variables are used to create the Web Server and WebSocket Server. These variables are used to handle the HTTP GET requests for various resources. server Web Server ws WebSocket Server processor Web Server Processor wsFrameInfo WebSocket Frame Information wsMask WebSocket Mask void
Referenced by onEvent.
void onEvent(AsyncWebSocket *server, AsyncWebSocketClient *client, AwsEventType type, void *arg, uint8_t *data, size_t len)
Web Server and WebSocket Server variables and constants initialization function.
This function initializes the Web Server and WebSocket Server variables and constants. This function initializes the Web Server and WebSocket Server variables and constants. server client type arg data len
References handleWebSocketMessage.
Referenced by setupRoutes.
void setupRoutes()
Setup Calls.
Setup the routes for the web server. This function defines the routes for handling HTTP GET requests for various resources such as HTML pages, CSS files, JS files, images, time adjustments, timer control, toggle actions, state actions, WiFi handlers, and timer handlers.
References handleHour, handleMinute, handleSecound, handleState, handleTimeAdjust, handleTimer, handleTimerControl, handleToggle, handleWifiIP, handleWifiQuality, handleWifiSSID, handleWifiTX, onEvent, processor, server, ws.
Referenced by setup.