MD_Web_Handlers.cpp
String handleTimer()
Definitions.
Get resistor. Timer handlers Handle Timer String This function handles the timer This function returns the timer in the format HH:MM:SS
References getTimerHour, getTimerMinute, getTimerSecound.
Referenced by processor, setupRoutes.
String handleHour()
Handle Hour.
Handle timer. String This function returns the timer hour
References getTimerHour.
Referenced by processor, setupRoutes.
String handleMinute()
Handle Minute.
Handle hour. String This function returns the timer minute
References getTimerMinute.
Referenced by processor, setupRoutes.
String handleSecound()
Handle Secound.
Handle minute. String This function returns the timer secound
References getTimerSecound.
Referenced by processor, setupRoutes.
String handleWifiQuality()
Handlers for Wifi Quality, SSID, TX and IP.
Handle secound. Handle Wifi Quality String This function returns the WiFi quality in percentage
References wifiQuality.
Referenced by processor, setupRoutes.
String handleWifiSSID()
Handle Wifi SSID.
Handle wifi quality. String This function returns the WiFi SSID
Referenced by processor, setupRoutes.
String handleWifiTX()
Handle Wifi TX.
Handle wifi SSID. String This function returns the WiFi TX power
Referenced by processor, setupRoutes.
String handleWifiIP()
Handle Wifi IP.
Handle wifi TX. String This function returns the WiFi IP address
Referenced by processor, setupRoutes.
String handleTimeAdjust(const String &adjustment)
Timer Add/Remove Time.
Handle wifi IP. Handle Time Adjust adjustment String This function adjusts the timer This function returns the adjustment message for the timer (add1s, add5s, add10s, add1m, add5m, add10m, rem1s, rem5s, rem10s, rem1m, rem5m, rem10m)
References add10m, add10s, add1m, add1s, add5m, add5s, rem10m, rem10s, rem1m, rem1s, rem5m, rem5s.
Referenced by setupRoutes.
String handleTimerControl(const String &control)
Timer Start/Stop/Reset.
Handle time adjustment. Handle Timer Control control String This function controls the timer This function returns the control message for the timer (start, stop, reset)
References OFF, ON, resetTimer, setTimer.
Referenced by setupRoutes.
String handleState(const String &state)
Handlers for Auto, Pump, WaterOut, Resistor, WaterIn and WaterMax With Response.
Handle timer control. Handle State state String This function handles the state of the variable (auto, manual, pump, waterOut, resistor, waterIn, waterMax, waterMin, waterAlarm) This function returns the state of the variable (auto, manual, pump, waterOut, resistor, waterIn, waterMax, waterMin, waterAlarm)
References getAlarm, getIndAuto, getManualMode, getPump, getResistor, getValv_Water_In, getValv_Water_Out, getWaterMax, getWaterMin.
Referenced by processor, setupRoutes.
String handleToggle(const String &toggle)
Handlers for Toggle Auto, Pump, waterOut, Resistor, WaterIn and WaterMax.
Handle state. Handle Toggle toggle String This function toggles the variable (auto, pump, waterOut, resistor, waterIn) This function returns the toggle message for the variable (auto, pump, waterOut, resistor, waterIn)
References toggleAutoModeWeb, togglePumpWeb, toggleResistorWeb, toggleValveWaterInWeb, toggleValveWaterOutWeb.
Referenced by setupRoutes.
String processor(const String &var)
Function to handle the HTTP requests for the variables.
Handle toggle. Processor var String This function processes the variables for the web server requests This function is called by the web server handle function (server.on) This function returns the variable value for the web server request
References handleHour, handleMinute, handleSecound, handleState, handleTimer, handleWifiIP, handleWifiQuality, handleWifiSSID, handleWifiTX.
Referenced by setupRoutes.