MD.h
ALARM_TIME_ON
TIMERS.
Defining timers for the alarm indicator blinking
Referenced by setIndAlarm.
ALARM_TIME_OFF
Referenced by setIndAlarm.
WIFI_MODE_OPTIONS
WIFI SERVICE.
WIFI Functions calls
Referenced by initWIFI.
void sendWiFiQuality()
MiddleWare Header.
Function prototypes
void toggleAutoMode()
Toggle the Auto Mode of the Machine using a switch connected to the ESP32 GPIO 4 (D4)
This function is used to toggle the Auto Mode of the Machine using a switch connected to the ESP32 GPIO 4 (D4)
References getAutoModeSW, OFF, toggleIndAuto.
Referenced by modeManagement.
void toggleIndAuto()
Toggle the Auto Mode of the Machine.
This function is used to toggle the Auto Mode of the Machine
References getIndAuto, OFF, setAutoModeWeb, setIndAuto, ws.
Referenced by toggleAutoMode.
void indicatorsManagement()
References getAlarmIND, getManualMode, getWaterMax, getWaterMin, setIndAlarm, setIndMan, setIndMax, setIndMin.
Referenced by destiler.
void modeManagement()
References getAutoModeWeb, getIndAuto, getManualMode, OFF, setAutoModeWeb, setIndAuto, setTimer, toggleAutoMode.
Referenced by destiler.
void updateOutputsWeb()
Output variables image.
FUNCTIONS BLOCK Update Outputs Web This function updates the outputs for the web interface. void
References getAlarm, getManualMode, getPump, getResistor, getValv_Water_In, getValv_Water_Out, getWaterMax, getWaterMin, outputVarsImageWeb.
Referenced by setup.
void toggleAutoModeWeb()
TOGGLES BLOCK.
Toggle Auto Mode Web This function toggles the auto mode. void
References getIndAuto, getManualMode, OFF, ON, setAutoModeWeb.
Referenced by handleToggle.
void togglePumpWeb()
Toggle Pump Web.
This function toggles the pump. void Toggle Pump
References getManualMode, getPumpWeb, OFF, ON, setPumpWeb, sPrintStr.
Referenced by handleToggle.
void toggleValveWaterInWeb()
Toggle Valve Water In Web.
This function toggles the water in valve. void Toggle Valve Water In
References getManualMode, getValv_Water_In, OFF, ON, setValveWaterInWeb.
Referenced by handleToggle.
void toggleValveWaterOutWeb()
Toggle Valve Water Out Web.
This function toggles the water out valve. void Toggle Valve Water Out
References getManualMode, getValv_Water_Out, OFF, ON, setValveWaterOutWeb.
Referenced by handleToggle.
void toggleResistorWeb()
Toggle Resistor Web.
This function toggles the resistor. void Toggle Resistor
References getManualMode, getResistor, OFF, ON, setResistorWeb.
Referenced by handleToggle.
void setAutoModeWeb(bool state)
SETS BLOCK.
Set the Auto Mode object This function sets the state of the auto mode. state void
References OFF, ON, outputVarsImageWeb, POS_IND_AUTO.
Referenced by modeManagement, toggleAutoModeWeb, toggleIndAuto.
void setPumpWeb(bool state)
Set the Pump object.
This function sets the state of the pump. state void
References OFF, ON, outputVarsImageWeb, POS_BMB.
Referenced by destiler, togglePumpWeb.
void setValveWaterInWeb(bool state)
Set the Valve Water In object.
This function sets the state of the water in valve. state void
References OFF, ON, outputVarsImageWeb, POS_VALV_WATER_IN.
Referenced by toggleValveWaterInWeb.
void setValveWaterOutWeb(bool state)
Set the Valve Water Out object.
This function sets the state of the water out valve. state void
References OFF, ON, outputVarsImageWeb, POS_VALV_WATER_OUT.
Referenced by toggleValveWaterOutWeb.
void setResistorWeb(bool state)
Set the Resistor object.
This function sets the state of the resistor. state void
References OFF, ON, outputVarsImageWeb, POS_RAQ.
Referenced by toggleResistorWeb.
bool getAutoModeWeb()
GETS BLOCK.
Get the Ind Max object This function returns the state of the max indicator. true false
References outputVarsImageWeb, POS_IND_AUTO.
Referenced by modeManagement.
bool getPumpWeb()
Get the Pump object.
This function returns the state of the water pump. true false
References outputVarsImageWeb, POS_BMB.
Referenced by destiler, togglePumpWeb.
bool getValv_Water_InWeb()
Get the Ind Alarm object.
This function returns the state of the alarm indicator. true false
References outputVarsImageWeb, POS_VALV_WATER_IN.
Referenced by destiler.
bool getValv_Water_OutWeb()
Get the Valv Water Out object.
This function returns the state of the water out valve. true false
References outputVarsImageWeb, POS_VALV_WATER_OUT.
Referenced by destiler.
bool getResistorWeb()
Get the Ind Min object.
This function returns the state of the min indicator. true false
References outputVarsImageWeb, POS_RAQ.
Referenced by destiler.
String handleTimer()
Handlers.
Handlers. Timer handlers Handle Timer String This function handles the timer This function returns the timer in the format HH:MM:SS
References getTimerHour, getTimerMinute, getTimerSecound.
Referenced by processor, setupRoutes.
String handleHour()
Handle Hour.
String This function returns the timer hour
References getTimerHour.
Referenced by processor, setupRoutes.
String handleMinute()
Handle Minute.
String This function returns the timer minute
References getTimerMinute.
Referenced by processor, setupRoutes.
String handleSecound()
Handle Secound.
String This function returns the timer secound
References getTimerSecound.
Referenced by processor, setupRoutes.
String handleWifiQuality()
Handlers for Wifi Quality, SSID, TX and IP.
Handle Wifi Quality String This function returns the WiFi quality in percentage
References wifiQuality.
Referenced by processor, setupRoutes.
String handleWifiSSID()
Handle Wifi SSID.
String This function returns the WiFi SSID
Referenced by processor, setupRoutes.
String handleWifiTX()
Handle Wifi TX.
String This function returns the WiFi TX power
Referenced by processor, setupRoutes.
String handleWifiIP()
Handle Wifi IP.
String This function returns the WiFi IP address
Referenced by processor, setupRoutes.
String handleTimeAdjust(const String &adjustment)
Timer Add/Remove Time.
Handle Time Adjust adjustment String This function adjusts the timer This function returns the adjustment message for the timer (add1s, add5s, add10s, add1m, add5m, add10m, rem1s, rem5s, rem10s, rem1m, rem5m, rem10m)
References add10m, add10s, add1m, add1s, add5m, add5s, rem10m, rem10s, rem1m, rem1s, rem5m, rem5s.
Referenced by setupRoutes.
String handleTimerControl(const String &control)
Timer Start/Stop/Reset.
Handle Timer Control control String This function controls the timer This function returns the control message for the timer (start, stop, reset)
References OFF, ON, resetTimer, setTimer.
Referenced by setupRoutes.
String handleState(const String &state)
Handlers for Auto, Pump, WaterOut, Resistor, WaterIn and WaterMax With Response.
Handle State state String This function handles the state of the variable (auto, manual, pump, waterOut, resistor, waterIn, waterMax, waterMin, waterAlarm) This function returns the state of the variable (auto, manual, pump, waterOut, resistor, waterIn, waterMax, waterMin, waterAlarm)
References getAlarm, getIndAuto, getManualMode, getPump, getResistor, getValv_Water_In, getValv_Water_Out, getWaterMax, getWaterMin.
Referenced by processor, setupRoutes.
String handleToggle(const String &toggle)
Handlers for Toggle Auto, Pump, waterOut, Resistor, WaterIn and WaterMax.
Handle Toggle toggle String This function toggles the variable (auto, pump, waterOut, resistor, waterIn) This function returns the toggle message for the variable (auto, pump, waterOut, resistor, waterIn)
References toggleAutoModeWeb, togglePumpWeb, toggleResistorWeb, toggleValveWaterInWeb, toggleValveWaterOutWeb.
Referenced by setupRoutes.
String processor(const String &var)
Function to handle the HTTP requests for the variables.
Processor var String This function processes the variables for the web server requests This function is called by the web server handle function (server.on) This function returns the variable value for the web server request
References handleHour, handleMinute, handleSecound, handleState, handleTimer, handleWifiIP, handleWifiQuality, handleWifiSSID, handleWifiTX.
Referenced by setupRoutes.
long webTimer(String op, int16_t amount)
Timer Functions calls.
Timer Functions calls. This function is responsible for managing the timer operations. op amount unsigned long
References flagTimerStatus, OFF, ON, sendTimer, setTimer, updateInterval.
Referenced by add10m, add10s, add1m, add1s, add5m, add5s, getTimerHour, getTimerMinute, getTimerSecound, loop2, rem10m, rem10s, rem1m, rem1s, rem5m, rem5s, resetTimer.
int getTimerSecound()
Timer for web operations.
Timer for web operations. int
References webTimer.
Referenced by destiler, handleSecound, handleTimer, sendTimer.
int getTimerMinute()
Get timer secound.
Get timer secound. int
References webTimer.
Referenced by destiler, handleMinute, handleTimer, sendTimer.
int getTimerHour()
Get timer minute.
Get timer minute. int
References webTimer.
Referenced by destiler, handleHour, handleTimer, sendTimer.
bool getTimerStatus()
Get timer hour.
Get timer hour. This function is called by the processor function in AP_Destiller.cpp true false
References flagTimerStatus.
Referenced by destiler, sendTimer.
void add1s()
Get timer status.
Get timer status.
References webTimer.
Referenced by handleTimeAdjust.
void add5s()
Add 1 secound to timer.
Add 1 secound to timer.
References webTimer.
Referenced by handleTimeAdjust.
void add10s()
Add 5 secounds to timer.
Add 5 secounds to timer.
References webTimer.
Referenced by handleTimeAdjust.
void add1m()
Add 10 secounds to timer.
Add 10 secounds to timer.
References webTimer.
Referenced by handleTimeAdjust.
void add5m()
Add 1 minute to timer.
Add 1 minute to timer.
References webTimer.
Referenced by handleTimeAdjust.
void add10m()
Add 5 minutes to timer.
Add 5 minutes to timer.
References webTimer.
Referenced by handleTimeAdjust.
void rem1s()
Add 10 minutes to timer.
Add 10 minutes to timer.
References webTimer.
Referenced by handleTimeAdjust.
void rem5s()
Remove 1 secound from timer.
Remove 1 secound from timer.
References webTimer.
Referenced by handleTimeAdjust.
void rem10s()
Remove 5 secounds from timer.
Remove 5 secounds from timer.
References webTimer.
Referenced by handleTimeAdjust.
void rem1m()
Remove 10 secounds from timer.
Remove 10 secounds from timer.
References webTimer.
Referenced by handleTimeAdjust.
void rem5m()
Remove 1 minute from timer.
Remove 1 minute from timer.
References webTimer.
Referenced by handleTimeAdjust.
void rem10m()
Remove 5 minutes from timer.
Remove 5 minutes from timer.
References webTimer.
Referenced by handleTimeAdjust.
void resetTimer()
Remove 10 minutes from timer.
Remove 10 minutes from timer.
References webTimer.
Referenced by handleTimerControl.
void setTimer(bool stat)
Reset timer.
Reset timer. stat
References flagTimerStatus, OFF, ON, sendTimer.
Referenced by handleTimerControl, modeManagement, webTimer.
void initSerial()
Set timer status.
SERIAL Serial Functions calls Set timer status. Initialize Serial Communications with the default baud rate of 9600 bps This function is used to initialize the Serial Communications with the default baud rate of 9600 bps This function is called in the setup() function of the main program This function is used to print the initial message to the Serial Terminal
References sPrintLnStr.
Referenced by setup.
void sPrint(char *abc)
Inicia a serial.
Inicia a serial. Print a string to the Serial Terminal abc This function is used to print a string to the Serial Terminal with no line break
void sPrintLn(char *abc)
Print string.
Print string. abc This function is used to print a string to the Serial Terminal with a line break
void sPrintStr(String abc)
Print string with new line.
Print string with new line. abc This function is used to print a string to the Serial Terminal with no line break
Referenced by connectToSoftAP, connectToWIFI, destiler, togglePumpWeb.
void sPrintNbr(int nbr)
Print string.
Print string. nbr This function is used to print a number to the Serial Terminal with no line break
Referenced by destiler.
void sPrintLnStr(String abc)
Print number.
Print number. abc This function is used to print a string to the Serial Terminal with a line break
Referenced by connectToSoftAP, connectToWIFI, destiler, initFS, initSerial, initWIFI, OnWiFiEvent, setIndAlarm, setIndAuto, setIndMan, setIndMax, setIndMin, setPump, setResistor, setValveWaterIn, setValveWaterOut.
void sPrintLnNbr(int nbr)
Print string with new line.
Print string with new line. nbr This function is used to print a number to the Serial Terminal with a line break
Referenced by destiler.
void test_IO()
Print number with new line.
Test I/Os Print number with new line. void
References DEBUG, delayT, OFF, ON, setIndAlarm, setIndAuto, setIndMan, setIndMax, setIndMin, setResistor, setValveWaterIn, setValveWaterOut, writeOutputs.
Referenced by setup.
bool initWIFI()
Initiate WiFi.
bool This function initiates the WiFi connection
References connectToSoftAP, connectToWIFI, sPrintLnStr, WIFI_MODE_OPTIONS.
Referenced by setup.
String wifiQuality()
Inicia o wifi.
Inicia o wifi. String This function returns the WiFi quality in percentage
References ws.
Referenced by connectToWIFI, destiler, handleWifiQuality.