MD_Serial.cpp
void initSerial()
Initialize Serial Terminal.
Set timer status. Initialize Serial Communications with the default baud rate of 9600 bps This function is used to initialize the Serial Communications with the default baud rate of 9600 bps This function is called in the setup() function of the main program This function is used to print the initial message to the Serial Terminal
References sPrintLnStr.
Referenced by setup.
void sPrint(char *abc)
Serial Print Functions.
Inicia a serial. Print a string to the Serial Terminal abc This function is used to print a string to the Serial Terminal with no line break
void sPrintLn(char *abc)
Print a string to the Serial Terminal with a line break.
Print string. abc This function is used to print a string to the Serial Terminal with a line break
void sPrintStr(String abc)
Print a string to the Serial Terminal.
Print string with new line. abc This function is used to print a string to the Serial Terminal with no line break
Referenced by connectToSoftAP, connectToWIFI, destiler, togglePumpWeb.
void sPrintLnStr(String abc)
Print a string to the Serial Terminal with a line break.
Print number. abc This function is used to print a string to the Serial Terminal with a line break
Referenced by connectToSoftAP, connectToWIFI, destiler, initFS, initSerial, initWIFI, OnWiFiEvent, setIndAlarm, setIndAuto, setIndMan, setIndMax, setIndMin, setPump, setResistor, setValveWaterIn, setValveWaterOut.
void sPrintNbr(int nbr)
Print a number to the Serial Terminal.
Print string. nbr This function is used to print a number to the Serial Terminal with no line break
Referenced by destiler.
void sPrintLnNbr(int nbr)
Print a number to the Serial Terminal with a line break.
Print string with new line. nbr This function is used to print a number to the Serial Terminal with a line break
Referenced by destiler.