MD_Timer.cpp
bool flagTimerStatus
Timer Functions.
Referenced by getTimerStatus, setTimer, webTimer.
unsigned long previousTimer
flag to timer status
unsigned long lastUpdateSent
const unsigned long updateInterval
Referenced by webTimer.
void sendTimer()
Send timer to web.
This function sends the timer to the web interface to update the timer display in the web interface. This function is called by the webTimer function in MD_Timer.cpp
References getTimerHour, getTimerMinute, getTimerSecound, getTimerStatus, ws.
Referenced by setTimer, webTimer.
long webTimer(String op, int16_t amount)
Web timer function to manage the timer operations in the web interface.
Timer Functions calls. This function is responsible for managing the timer operations. op amount unsigned long
References flagTimerStatus, OFF, ON, sendTimer, setTimer, updateInterval.
Referenced by add10m, add10s, add1m, add1s, add5m, add5s, getTimerHour, getTimerMinute, getTimerSecound, loop2, rem10m, rem10s, rem1m, rem1s, rem5m, rem5s, resetTimer.
bool getTimerStatus()
Get the Timer Status object to get the timer status (ON/OFF)
Get timer hour. This function is called by the processor function in AP_Destiller.cpp true false
References flagTimerStatus.
Referenced by destiler, sendTimer.
int getTimerSecound()
Get the Timer Secound object to get the timer secound.
Timer for web operations. int
References webTimer.
Referenced by destiler, handleSecound, handleTimer, sendTimer.
int getTimerMinute()
Get the Timer Minute object to get the timer minute.
Get timer secound. int
References webTimer.
Referenced by destiler, handleMinute, handleTimer, sendTimer.
int getTimerHour()
Get the Timer Hour object to get the timer hour.
Get timer minute. int
References webTimer.
Referenced by destiler, handleHour, handleTimer, sendTimer.
void setTimer(bool stat)
Set the Timer object to set the timer status (ON/OFF)
Reset timer. stat
References flagTimerStatus, OFF, ON, sendTimer.
Referenced by handleTimerControl, modeManagement, webTimer.
void add1s()
Add 1 secound to timer.
Get timer status.
References webTimer.
Referenced by handleTimeAdjust.
void add5s()
Add 5 secounds to timer.
Add 1 secound to timer.
References webTimer.
Referenced by handleTimeAdjust.
void add10s()
Add 10 secounds to timer.
Add 5 secounds to timer.
References webTimer.
Referenced by handleTimeAdjust.
void add1m()
Add 1 minute to timer.
Add 10 secounds to timer.
References webTimer.
Referenced by handleTimeAdjust.
void add5m()
Add 5 minutes to timer.
Add 1 minute to timer.
References webTimer.
Referenced by handleTimeAdjust.
void add10m()
Add 10 minutes to timer.
Add 5 minutes to timer.
References webTimer.
Referenced by handleTimeAdjust.
void rem1s()
Remove 1 secound from timer.
Add 10 minutes to timer.
References webTimer.
Referenced by handleTimeAdjust.
void rem5s()
Remove 5 secounds from timer.
Remove 1 secound from timer.
References webTimer.
Referenced by handleTimeAdjust.
void rem10s()
Remove 10 secounds from timer.
Remove 5 secounds from timer.
References webTimer.
Referenced by handleTimeAdjust.
void rem1m()
Remove 1 minute from timer.
Remove 10 secounds from timer.
References webTimer.
Referenced by handleTimeAdjust.
void rem5m()
Remove 5 minutes from timer.
Remove 1 minute from timer.
References webTimer.
Referenced by handleTimeAdjust.
void rem10m()
Remove 10 minutes from timer.
Remove 5 minutes from timer.
References webTimer.
Referenced by handleTimeAdjust.
void resetTimer()
Reset timer.
Remove 10 minutes from timer.
References webTimer.
Referenced by handleTimerControl.