MD_Web_IO_Mngmnt.cpp
uint8_t outputVarsImageWeb[9][9]
Referenced by getAutoModeWeb, getPumpWeb, getResistorWeb, getValv_Water_InWeb, getValv_Water_OutWeb, setAutoModeWeb, setPumpWeb, setResistorWeb, setValveWaterInWeb, setValveWaterOutWeb, updateOutputsWeb.
void updateOutputsWeb()
Output variables image.
FUNCTIONS BLOCK Update Outputs Web This function updates the outputs for the web interface. void
References getAlarm, getManualMode, getPump, getResistor, getValv_Water_In, getValv_Water_Out, getWaterMax, getWaterMin, outputVarsImageWeb.
Referenced by setup.
bool getAutoModeWeb()
GETS BLOCK.
Get the Ind Max object This function returns the state of the max indicator. true false
References outputVarsImageWeb, POS_IND_AUTO.
Referenced by modeManagement.
bool getResistorWeb()
Get the Ind Min object.
This function returns the state of the min indicator. true false
References outputVarsImageWeb, POS_RAQ.
Referenced by destiler.
bool getValv_Water_InWeb()
Get the Ind Alarm object.
This function returns the state of the alarm indicator. true false
References outputVarsImageWeb, POS_VALV_WATER_IN.
Referenced by destiler.
bool getValv_Water_OutWeb()
Get the Valv Water Out object.
This function returns the state of the water out valve. true false
References outputVarsImageWeb, POS_VALV_WATER_OUT.
Referenced by destiler.
bool getPumpWeb()
Get the Pump object.
This function returns the state of the water pump. true false
References outputVarsImageWeb, POS_BMB.
Referenced by destiler, togglePumpWeb.
void setAutoModeWeb(bool state)
SETS BLOCK.
Set the Auto Mode object This function sets the state of the auto mode. state void
References OFF, ON, outputVarsImageWeb, POS_IND_AUTO.
Referenced by modeManagement, toggleAutoModeWeb, toggleIndAuto.
void setPumpWeb(bool state)
Set the Pump object.
This function sets the state of the pump. state void
References OFF, ON, outputVarsImageWeb, POS_BMB.
Referenced by destiler, togglePumpWeb.
void setValveWaterInWeb(bool state)
Set the Valve Water In object.
This function sets the state of the water in valve. state void
References OFF, ON, outputVarsImageWeb, POS_VALV_WATER_IN.
Referenced by toggleValveWaterInWeb.
void setValveWaterOutWeb(bool state)
Set the Valve Water Out object.
This function sets the state of the water out valve. state void
References OFF, ON, outputVarsImageWeb, POS_VALV_WATER_OUT.
Referenced by toggleValveWaterOutWeb.
void setResistorWeb(bool state)
Set the Resistor object.
This function sets the state of the resistor. state void
References OFF, ON, outputVarsImageWeb, POS_RAQ.
Referenced by toggleResistorWeb.
void toggleAutoModeWeb()
TOGGLES BLOCK.
Toggle Auto Mode Web This function toggles the auto mode. void
References getIndAuto, getManualMode, OFF, ON, setAutoModeWeb.
Referenced by handleToggle.
void togglePumpWeb()
Toggle Pump Web.
This function toggles the pump. void Toggle Pump
References getManualMode, getPumpWeb, OFF, ON, setPumpWeb, sPrintStr.
Referenced by handleToggle.
void toggleValveWaterInWeb()
Toggle Valve Water In Web.
This function toggles the water in valve. void Toggle Valve Water In
References getManualMode, getValv_Water_In, OFF, ON, setValveWaterInWeb.
Referenced by handleToggle.
void toggleValveWaterOutWeb()
Toggle Valve Water Out Web.
This function toggles the water out valve. void Toggle Valve Water Out
References getManualMode, getValv_Water_Out, OFF, ON, setValveWaterOutWeb.
Referenced by handleToggle.
void toggleResistorWeb()
Toggle Resistor Web.
This function toggles the resistor. void Toggle Resistor
References getManualMode, getResistor, OFF, ON, setResistorWeb.
Referenced by handleToggle.