MD_IO.cpp
void toggleIndAuto()
Toggle the Auto Mode of the Machine.
Toggle auto mode. This function is used to toggle the Auto Mode of the Machine
References getIndAuto, OFF, setAutoModeWeb, setIndAuto, ws.
Referenced by toggleAutoMode.
void toggleAutoMode()
Toggle the Auto Mode of the Machine using a switch connected to the ESP32 GPIO 4 (D4)
MiddleWare Header. This function is used to toggle the Auto Mode of the Machine using a switch connected to the ESP32 GPIO 4 (D4)
References getAutoModeSW, OFF, toggleIndAuto.
Referenced by modeManagement.
void indicatorsManagement()
Toggle auto indicator.
References getAlarmIND, getManualMode, getWaterMax, getWaterMin, setIndAlarm, setIndMan, setIndMax, setIndMin.
Referenced by destiler.
void modeManagement()
Indicators management.
References getAutoModeWeb, getIndAuto, getManualMode, OFF, setAutoModeWeb, setIndAuto, setTimer, toggleAutoMode.
Referenced by destiler.