MD_wifi.cpp
const char* soft_ap_ssid
Referenced by connectToSoftAP.
const char* soft_ap_password
Referenced by connectToSoftAP.
void OnWiFiEvent(WiFiEvent_t event)
WiFi Event Handler.
This function handles the WiFi events event void
References sPrintLnStr.
Referenced by connectToSoftAP.
String wifiQuality()
WiFi Quality.
Inicia o wifi. String This function returns the WiFi quality in percentage
References ws.
Referenced by connectToWIFI, destiler, handleWifiQuality.
void connectToWIFI()
Connect to WiFi.
void This function connects the ESP32 to a WiFi network
References server, sPrintLnStr, sPrintStr, wifiQuality.
Referenced by initWIFI.
void connectToSoftAP()
Connect to SoftAP.
void This function creates a Soft Access Point The IP Address of the ESP32 Soft Access Point is set to: 192.168.100.100
References OnWiFiEvent, soft_ap_password, soft_ap_ssid, sPrintLnStr, sPrintStr.
Referenced by initWIFI.
bool initWIFI()
Initiate WiFi.
bool This function initiates the WiFi connection
References connectToSoftAP, connectToWIFI, sPrintLnStr, WIFI_MODE_OPTIONS.
Referenced by setup.