OS.h
DEBUGlog
Debug mode.
Referenced by destiler.
PIN_SW_AUTO
I/O Map Header.
Input Pins Definitions
Referenced by initPinsInputs.
PIN_SALARM
Referenced by initPinsInputs.
PIN_SW_MAN
Referenced by initPinsInputs.
PIN_SMIN
Referenced by initPinsInputs.
PIN_SMAX
Referenced by initPinsInputs.
PIN_INPUT_COUNT
Referenced by readInputs.
POS_SW_MAN
Referenced by getManualMode.
POS_SMIN
Referenced by getWaterMin.
POS_SMAX
Referenced by getWaterMax.
POS_SW_AUTO
Referenced by getAutoModeSW.
POS_SALARM
Referenced by getAlarmIND.
PIN_RAQ
Output Pins Definitions.
Referenced by initPinsOutputs.
PIN_BMB
Referenced by initPinsOutputs.
PIN_VALV_WATER_OUT
Referenced by initPinsOutputs.
PIN_VALV_WATER_IN
Referenced by initPinsOutputs.
PIN_IND_ALARM
Referenced by initPinsOutputs.
PIN_IND_MIN
Referenced by initPinsOutputs.
PIN_IND_MAX
Referenced by initPinsOutputs.
PIN_IND_AUTO
Referenced by initPinsOutputs.
PIN_IND_MAN
Referenced by initPinsOutputs.
PIN_OUTPUT_COUNT
Referenced by writeOutputs.
POS_RAQ
Referenced by getResistor, getResistorWeb, setResistor, setResistorWeb.
POS_BMB
Referenced by getPump, getPumpWeb, setPump, setPumpWeb.
POS_VALV_WATER_OUT
Referenced by getValv_Water_Out, getValv_Water_OutWeb, setValveWaterOut, setValveWaterOutWeb.
POS_VALV_WATER_IN
Referenced by getValv_Water_In, getValv_Water_InWeb, setValveWaterIn, setValveWaterInWeb.
POS_IND_ALARM
Referenced by setIndAlarm.
POS_IND_MIN
Referenced by setIndMin.
POS_IND_MAX
Referenced by setIndMax.
POS_IND_AUTO
Referenced by getAutoModeWeb, getIndAuto, setAutoModeWeb, setIndAuto.
POS_IND_MAN
Referenced by setIndMan.
ON
ON/OFF Definitions for I/O pins (HIGH/LOW)
Referenced by destiler, handleTimerControl, setAutoModeWeb, setIndAlarm, setIndAuto, setIndMan, setIndMax, setIndMin, setPump, setPumpWeb, setResistor, setResistorWeb, setTimer, setValveWaterIn, setValveWaterInWeb, setValveWaterOut, setValveWaterOutWeb, test_IO, toggleAutoModeWeb, togglePumpWeb, toggleResistorWeb, toggleValveWaterInWeb, toggleValveWaterOutWeb, webTimer.
OFF
Referenced by destiler, handleTimerControl, modeManagement, setAutoModeWeb, setIndAlarm, setIndAuto, setIndMan, setIndMax, setIndMin, setPump, setPumpWeb, setResistor, setResistorWeb, setTimer, setValveWaterIn, setValveWaterInWeb, setValveWaterOut, setValveWaterOutWeb, test_IO, toggleAutoMode, toggleAutoModeWeb, toggleIndAuto, togglePumpWeb, toggleResistorWeb, toggleValveWaterInWeb, toggleValveWaterOutWeb, webTimer.
AsyncWebSocket ws
Libraries.
Wifi Libraries Async Libraries SPIFFS Libraries
Referenced by loop2, sendTimer, setIndAlarm, setIndAuto, setIndMan, setIndMax, setIndMin, setPump, setResistor, setup, setupRoutes, setValveWaterIn, setValveWaterOut, toggleIndAuto, wifiQuality.
AsyncWebServer server
WebSocket.
Referenced by connectToWIFI, setup, setupRoutes.
bool DEBUG
WebServer.
Referenced by setIndAlarm, setIndAuto, setIndMan, setIndMax, setIndMin, setPump, setResistor, setValveWaterIn, setValveWaterOut, test_IO.
void loop2(void *pvParameters)
MAIN.
MAIN. This function is responsible for running the second core operation. Initiate WIFI Cleanup clients WebTimer function initWIFI() ws.cleanupClients() webTimer() pvParameters
References webTimer, ws.
Referenced by initMultiCore.
void initMultiCore()
Main loop to run in core 1.
Multicore Main loop to run in core 1. <Function to initiate the 2nd core>
References loop2.
Referenced by setup.
void initFS()
LittleFS.
LittleFS. Initialize File System (SPIFFS) This function is responsible for initializing the File System (SPIFFS). Initialize SPIFFS void initFS();
References sPrintLnStr.
Referenced by setup.
void initPinsOutputs()
Inicia o sistema de arquivos.
I/O I/O Functions calls Inicia o sistema de arquivos. Configure GPIOs as OUTPUTs This function configures the GPIOs as OUTPUTs. The GPIOs are used to control the indicators, valves, pump, and resistor.
References PIN_BMB, PIN_IND_ALARM, PIN_IND_AUTO, PIN_IND_MAN, PIN_IND_MAX, PIN_IND_MIN, PIN_RAQ, PIN_VALV_WATER_IN, PIN_VALV_WATER_OUT.
Referenced by setup.
void initPinsInputs()
Inicia os outputs.
Inicia os outputs. Configure GPIOs as INPUTs This function configures the GPIOs as INPUTs. The GPIOs are used to read the state of the switches and sensors.
References PIN_SALARM, PIN_SMAX, PIN_SMIN, PIN_SW_AUTO, PIN_SW_MAN.
Referenced by setup.
bool getWaterMax()
Inicia os inputs.
Inicia os inputs. Get the Water Max object This function returns the state of the water max sensor. true false
References inputVarsImage, POS_SMAX.
Referenced by destiler, handleState, indicatorsManagement, setIndMax, updateOutputsWeb.
bool getWaterMin()
Retorna estado do sensor de agua de maximo.
Retorna estado do sensor de agua de maximo. This function returns the state of the water min sensor. true false
References inputVarsImage, POS_SMIN.
Referenced by destiler, handleState, indicatorsManagement, setIndMin, updateOutputsWeb.
bool getAlarm()
Retorna estado do sensor de agua de minimo.
Retorna estado do sensor de agua de minimo. This function returns the state of the alarm. true false
References ALARM_STATE.
Referenced by destiler, handleState, setIndAlarm, updateOutputsWeb.
bool getAlarmIND()
Retorna estado do alarme.
Retorna estado do alarme. This function returns the state of the alarm. true false
References inputVarsImage, POS_SALARM.
Referenced by indicatorsManagement.
bool getIndAuto()
Retorna estado do indicador de alarme.
Retorna estado do indicador de alarme. This function returns the state of the max indicator. true false
References outputVarsImage, POS_IND_AUTO.
Referenced by destiler, handleState, modeManagement, setIndAuto, toggleAutoModeWeb, toggleIndAuto.
bool getAutoModeSW()
Retorna estado do modo auto.
Retorna estado do modo auto. This function returns the state of the auto mode switch. true false
References inputVarsImage, POS_SW_AUTO.
Referenced by toggleAutoMode.
bool getManualMode()
Retorna estado do interruptor auto.
Retorna estado do interruptor auto. This function returns the state of the manual mode switch. true false
References inputVarsImage, POS_SW_MAN.
Referenced by destiler, handleState, indicatorsManagement, modeManagement, setIndMan, toggleAutoModeWeb, togglePumpWeb, toggleResistorWeb, toggleValveWaterInWeb, toggleValveWaterOutWeb, updateOutputsWeb.
bool getResistor()
Retorna estado do botao manual.
Retorna estado do botao manual. This function returns the state of the min indicator. true false
References outputVarsImage, POS_RAQ.
Referenced by destiler, handleState, setResistor, toggleResistorWeb, updateOutputsWeb.
bool getValv_Water_In()
Retorna estado do resistor.
Retorna estado do resistor. This function returns the state of the alarm indicator. true false
References outputVarsImage, POS_VALV_WATER_IN.
Referenced by destiler, handleState, setValveWaterIn, toggleValveWaterInWeb, updateOutputsWeb.
bool getValv_Water_Out()
Retorna estado da entrada de agua.
Retorna estado da entrada de agua. This function returns the state of the water out valve. true false
References outputVarsImage, POS_VALV_WATER_OUT.
Referenced by destiler, handleState, setValveWaterOut, toggleValveWaterOutWeb, updateOutputsWeb.
bool getPump()
Retorna estado da valvula de vapor.
Retorna estado da valvula de vapor. This function returns the state of the water pump. true false
References outputVarsImage, POS_BMB.
Referenced by destiler, handleState, setPump, updateOutputsWeb.
void setIndMax(bool state)
Retorna estado da bomba de agua.
Retorna estado da bomba de agua. Set the Ind Max object This function sets the state of the max indicator. state void
References DEBUG, getWaterMax, OFF, ON, outputVarsImage, POS_IND_MAX, sPrintLnStr, ws.
Referenced by indicatorsManagement, test_IO.
void setIndMin(bool state)
Liga/desliga o indicador luminoso nivel agua maximo.
Liga/desliga o indicador luminoso nivel agua maximo. This function sets the state of the min indicator. state void
References DEBUG, getWaterMin, OFF, ON, outputVarsImage, POS_IND_MIN, sPrintLnStr, ws.
Referenced by indicatorsManagement, test_IO.
void setIndAlarm(bool state)
Liga/desliga o indicador luminoso nivel agua minimo.
Liga/desliga o indicador luminoso nivel agua minimo. This function sets the state of the alarm indicator. state void
References ALARM_STATE, ALARM_TIME_OFF, ALARM_TIME_ON, DEBUG, getAlarm, OFF, ON, outputVarsImage, POS_IND_ALARM, sPrintLnStr, ws.
Referenced by indicatorsManagement, test_IO.
void setIndMan(bool state)
Liga/desliga o indicador luminoso alarme.
Liga/desliga o indicador luminoso alarme. This function sets the state of the manual indicator. state void
References DEBUG, getManualMode, OFF, ON, outputVarsImage, POS_IND_MAN, sPrintLnStr, ws.
Referenced by indicatorsManagement, test_IO.
void setPump(bool state)
Liga/desliga o indicador luminoso modo manual.
Liga/desliga o indicador luminoso modo manual. This function sets the state of the pump. state void
References DEBUG, getPump, OFF, ON, outputVarsImage, POS_BMB, sPrintLnStr, ws.
Referenced by destiler.
void setValveWaterIn(bool state)
Liga/desliga o indicador luminoso da bomba de agua.
Liga/desliga o indicador luminoso da bomba de agua. This function sets the state of the water in valve. state void
References DEBUG, getValv_Water_In, OFF, ON, outputVarsImage, POS_VALV_WATER_IN, sPrintLnStr, ws.
Referenced by destiler, test_IO.
void setValveWaterOut(bool state)
Liga/desliga o indicador luminoso da valvula 1.
Liga/desliga o indicador luminoso da valvula 1. This function sets the state of the water out valve. state void
References DEBUG, getValv_Water_Out, OFF, ON, outputVarsImage, POS_VALV_WATER_OUT, sPrintLnStr, ws.
Referenced by destiler, test_IO.
void setResistor(bool state)
Liga/desliga o indicador luminoso da valvula 2.
Liga/desliga o indicador luminoso da valvula 2. This function sets the state of the resistor. state void
References DEBUG, getResistor, OFF, ON, outputVarsImage, POS_RAQ, sPrintLnStr, ws.
Referenced by destiler, test_IO.
void setIndAuto(bool state1)
Liga/desliga o indicador luminoso da resistencia.
Liga/desliga o indicador luminoso da resistencia. This function sets the state of the auto mode. state void
References DEBUG, getIndAuto, OFF, ON, outputVarsImage, POS_IND_AUTO, sPrintLnStr, ws.
Referenced by modeManagement, test_IO, toggleIndAuto.
void writeOutputs()
Liga/desliga o modo auto.
Liga/desliga o modo auto. Write all outputs from the image array to the GPIOs This function writes all the outputs from the image array to the GPIOs. The image array is used to store the current state of the inputs and outputs.
References outputVarsImage, outputVarsPINs, PIN_OUTPUT_COUNT.
Referenced by loop, test_IO.
void readInputs()
Alarm state.
Read ESP32 GPIOs and stores in the image array Read all inputs and store in the image array This function reads all the inputs and stores them in the image array. The image array is used to store the current state of the inputs and outputs.
References inputVarsImage, inputVarsPINs, PIN_INPUT_COUNT.
Referenced by loop, setup.