OS_GPIO.cpp
uint8_t inputVarsImage[5][5]
GPIO Images.
Referenced by getAlarmIND, getAutoModeSW, getManualMode, getWaterMax, getWaterMin, readInputs.
const uint8_t inputVarsPINs[][]
Input variables image.
Referenced by readInputs.
uint8_t outputVarsImage[9][9]
Input variables pins.
Referenced by getIndAuto, getPump, getResistor, getValv_Water_In, getValv_Water_Out, setIndAlarm, setIndAuto, setIndMan, setIndMax, setIndMin, setPump, setResistor, setValveWaterIn, setValveWaterOut, writeOutputs.
const uint8_t outputVarsPINs[][]
Output variables image.
Referenced by writeOutputs.
bool ALARM_STATE
Output variables pins.
Referenced by getAlarm, setIndAlarm.
void readInputs()
Alarm state.
Read ESP32 GPIOs and stores in the image array Read all inputs and store in the image array This function reads all the inputs and stores them in the image array. The image array is used to store the current state of the inputs and outputs.
References inputVarsImage, inputVarsPINs, PIN_INPUT_COUNT.
Referenced by loop, setup.
void writeOutputs()
Write Outputs from array image to GPIO.
Liga/desliga o modo auto. Write all outputs from the image array to the GPIOs This function writes all the outputs from the image array to the GPIOs. The image array is used to store the current state of the inputs and outputs.
References outputVarsImage, outputVarsPINs, PIN_OUTPUT_COUNT.
Referenced by loop, test_IO.
void initPinsInputs()
Configure GPIOs as INPUT.
Inicia os outputs. Configure GPIOs as INPUTs This function configures the GPIOs as INPUTs. The GPIOs are used to read the state of the switches and sensors.
References PIN_SALARM, PIN_SMAX, PIN_SMIN, PIN_SW_AUTO, PIN_SW_MAN.
Referenced by setup.
void initPinsOutputs()
Configure GPIOs as OUTPUTs.
Inicia o sistema de arquivos. Configure GPIOs as OUTPUTs This function configures the GPIOs as OUTPUTs. The GPIOs are used to control the indicators, valves, pump, and resistor.
References PIN_BMB, PIN_IND_ALARM, PIN_IND_AUTO, PIN_IND_MAN, PIN_IND_MAX, PIN_IND_MIN, PIN_RAQ, PIN_VALV_WATER_IN, PIN_VALV_WATER_OUT.
Referenced by setup.
bool getWaterMax()
GETS BLOCK.
Inicia os inputs. Get the Water Max object This function returns the state of the water max sensor. true false
References inputVarsImage, POS_SMAX.
Referenced by destiler, handleState, indicatorsManagement, setIndMax, updateOutputsWeb.
bool getWaterMin()
Get the Water Min object.
Retorna estado do sensor de agua de maximo. This function returns the state of the water min sensor. true false
References inputVarsImage, POS_SMIN.
Referenced by destiler, handleState, indicatorsManagement, setIndMin, updateOutputsWeb.
bool getAlarm()
Get the Alarm object.
Retorna estado do sensor de agua de minimo. This function returns the state of the alarm. true false
References ALARM_STATE.
Referenced by destiler, handleState, setIndAlarm, updateOutputsWeb.
bool getAlarmIND()
Get the Alarm State object.
Retorna estado do alarme. This function returns the state of the alarm. true false
References inputVarsImage, POS_SALARM.
Referenced by indicatorsManagement.
bool getAutoModeSW()
Get the Auto Mode SW object.
Retorna estado do modo auto. This function returns the state of the auto mode switch. true false
References inputVarsImage, POS_SW_AUTO.
Referenced by toggleAutoMode.
bool getManualMode()
Get the Manual Mode object.
Retorna estado do interruptor auto. This function returns the state of the manual mode switch. true false
References inputVarsImage, POS_SW_MAN.
Referenced by destiler, handleState, indicatorsManagement, modeManagement, setIndMan, toggleAutoModeWeb, togglePumpWeb, toggleResistorWeb, toggleValveWaterInWeb, toggleValveWaterOutWeb, updateOutputsWeb.
bool getIndAuto()
Get the Ind Max object.
Retorna estado do indicador de alarme. This function returns the state of the max indicator. true false
References outputVarsImage, POS_IND_AUTO.
Referenced by destiler, handleState, modeManagement, setIndAuto, toggleAutoModeWeb, toggleIndAuto.
bool getResistor()
Get the Ind Min object.
Retorna estado do botao manual. This function returns the state of the min indicator. true false
References outputVarsImage, POS_RAQ.
Referenced by destiler, handleState, setResistor, toggleResistorWeb, updateOutputsWeb.
bool getValv_Water_In()
Get the Ind Alarm object.
Retorna estado do resistor. This function returns the state of the alarm indicator. true false
References outputVarsImage, POS_VALV_WATER_IN.
Referenced by destiler, handleState, setValveWaterIn, toggleValveWaterInWeb, updateOutputsWeb.
bool getValv_Water_Out()
Get the Valv Water Out object.
Retorna estado da entrada de agua. This function returns the state of the water out valve. true false
References outputVarsImage, POS_VALV_WATER_OUT.
Referenced by destiler, handleState, setValveWaterOut, toggleValveWaterOutWeb, updateOutputsWeb.
bool getPump()
Get the Pump object.
Retorna estado da valvula de vapor. This function returns the state of the water pump. true false
References outputVarsImage, POS_BMB.
Referenced by destiler, handleState, setPump, updateOutputsWeb.
void setIndMax(bool state)
SETS BLOCK.
Retorna estado da bomba de agua. Set the Ind Max object This function sets the state of the max indicator. state void
References DEBUG, getWaterMax, OFF, ON, outputVarsImage, POS_IND_MAX, sPrintLnStr, ws.
Referenced by indicatorsManagement, test_IO.
void setIndMin(bool state)
Set the Ind Min object.
Liga/desliga o indicador luminoso nivel agua maximo. This function sets the state of the min indicator. state void
References DEBUG, getWaterMin, OFF, ON, outputVarsImage, POS_IND_MIN, sPrintLnStr, ws.
Referenced by indicatorsManagement, test_IO.
void setIndAlarm(bool state)
Set the Ind Alarm object.
Liga/desliga o indicador luminoso nivel agua minimo. This function sets the state of the alarm indicator. state void
References ALARM_STATE, ALARM_TIME_OFF, ALARM_TIME_ON, DEBUG, getAlarm, OFF, ON, outputVarsImage, POS_IND_ALARM, sPrintLnStr, ws.
Referenced by indicatorsManagement, test_IO.
void setIndMan(bool state)
Set the Ind Man object.
Liga/desliga o indicador luminoso alarme. This function sets the state of the manual indicator. state void
References DEBUG, getManualMode, OFF, ON, outputVarsImage, POS_IND_MAN, sPrintLnStr, ws.
Referenced by indicatorsManagement, test_IO.
void setIndAuto(bool state)
Set the Auto Mode object.
Liga/desliga o indicador luminoso da resistencia. This function sets the state of the auto mode. state void
References DEBUG, getIndAuto, OFF, ON, outputVarsImage, POS_IND_AUTO, sPrintLnStr, ws.
Referenced by modeManagement, test_IO, toggleIndAuto.
void setPump(bool state)
Set the Pump object.
Liga/desliga o indicador luminoso modo manual. This function sets the state of the pump. state void
References DEBUG, getPump, OFF, ON, outputVarsImage, POS_BMB, sPrintLnStr, ws.
Referenced by destiler.
void setValveWaterIn(bool state)
Set the Valve Water In object.
Liga/desliga o indicador luminoso da bomba de agua. This function sets the state of the water in valve. state void
References DEBUG, getValv_Water_In, OFF, ON, outputVarsImage, POS_VALV_WATER_IN, sPrintLnStr, ws.
Referenced by destiler, test_IO.
void setValveWaterOut(bool state)
Set the Valve Water Out object.
Liga/desliga o indicador luminoso da valvula 1. This function sets the state of the water out valve. state void
References DEBUG, getValv_Water_Out, OFF, ON, outputVarsImage, POS_VALV_WATER_OUT, sPrintLnStr, ws.
Referenced by destiler, test_IO.
void setResistor(bool state)
Set the Resistor object.
Liga/desliga o indicador luminoso da valvula 2. This function sets the state of the resistor. state void
References DEBUG, getResistor, OFF, ON, outputVarsImage, POS_RAQ, sPrintLnStr, ws.
Referenced by destiler, test_IO.